### ISSUE TITLE
Doesn't seem to work at all anymore.

### ISSUE THREAD

**Issue by Kommynct** [KosmosisDire/ChangeFOVSettings#1]
Trying it out using r2modman, it does nothing in-game for me.

**Comment by KosmosisDire** [comment]
Try going to the settings, there should be options there for it (It's possible it's set to the default FOV) . If that isn't there then the mod isn't actually installed or active for some reason. There haven't been any updates for a while so nothing should have changed

**Comment by Kommynct** [comment]
Nope, it's there, it's just when I move the slider nothing happens at all.

**Comment by KosmosisDire** [comment]
Do you have any other mods?

**Comment by Kommynct** [comment]
Okay, it conflicts with one of my mods because disabling everything else fixed it... now to find out what, thanks! will report back with the conflict

Should have really tried that first... my bad.

**Comment by Kommynct** [comment]
https://github.com/JohnEdwa/RTAutoSprintExtended

^^the culprit is here.

**Comment by Kommynct** [comment]
https://github.com/JohnEdwa/RTAutoSprintExtended/issues/15
